### ISSUE TITLE
Wtyczka nie działa win11 QGIS 3.24.3

### ISSUE THREAD

**Issue by draken76** [MarcinLebiecki/BDOT10k_GML_SHP#4]
Nowy komputer, windows11 PRO 21H2 , QGIS 3.24.3
Nie można wczytać wtyczki 'BDOT10k_GML_SHP_Loader' z powodu błędu wywołania jej metody classFactory() 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/KiziaMizia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\BDOT10k_GML_SHP_Loader\__init__.py", line 36, in classFactory
    return BDOT10k_GML_SHP_Loader(iface)
  File "C:\Users/KiziaMizia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\BDOT10k_GML_SHP_Loader\BDOT10k_GML_SHP_Loader.py", line 57, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable

Wersja Pythona: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Wersja QGIS: 3.24.3-Tisler Tisler, cf22b74e

**Comment by MarcinLebiecki** [comment]
Proszę o weryfikację z najnowszą wersją wtyczki - v 2.0.1
